USE nwind13ke;
-- 1. Mennyit tett zsebre a tulaj (a cég eredménye eladási ár-raktári ár - költségek) 1995-ben,
--  ha az összes költséget adóparadicsomi körülmények között az összes fizetés + annak 10%-a fedezi?

SELECT
   
   SUM((rr.Egységár - t.Egységár)* (1- rr.Engedmény) * rr.Mennyiség)
     - SUM( a.Fizetés * 1.2) - SUM( a.Fizetés * 12) AS 'Nyereség ?'
  
  FROM termékek t
INNER JOIN rendelésrészletei rr ON t.Termékkód = rr.Termékkód
INNER JOIN rendelések r ON rr.Rendeléskód = r.Rendeléskód
INNER JOIN alkalmazottak a ON r.Alkalmazottkód = a.Alkalmazottkód
WHERE YEAR( r.RendelésDátuma) = 1995;

-- A raktáron levõ termékek egységára magasabb, mint az eladási ár,
--  ezért negatív a haszon(lehet, hogy pénzmosodára leltünk)
-- --------------------------------------------------------------------------------------


-- 2. Írja ki bevétel szerint növekvõ sorrendben, melyik fuvarozó mennyit keresett összesen!

SELECT
  s.Cégnév, SUM( r.SzállításiKöltség) AS Bevétel
  
  FROM szállítók s
INNER JOIN termékek t ON s.Szállítókód = t.Szállítókód
INNER JOIN rendelésrészletei rr ON t.Termékkód = rr.Termékkód
INNER JOIN rendelések r ON rr.Rendeléskód = r.Rendeléskód
GROUP BY s.Szállítókód
ORDER BY Bevétel;

-- -------------------------------------------------------------------------------------------------------------------

-- 3. Írja ki, mely termék fogyott jobban a 4 és 5-ös kódú terméknél 1995. elsõ két negyedévében!

SELECT rr.Termékkód, SUM(rr.Mennyiség) AS össz FROM rendelések r
INNER JOIN rendelésrészletei rr ON r.Rendeléskód = rr.Rendeléskód
WHERE YEAR( r.RendelésDátuma) = 1995  AND MONTH( r.RendelésDátuma) BETWEEN 1 AND 6
GROUP BY rr.Termékkód
HAVING össz >ANY (
SELECT  
  SUM(rr.Mennyiség)
FROM rendelésrészletei rr
INNER JOIN termékek t
    ON rr.Termékkód = t.Termékkód
INNER JOIN rendelések r
  ON rr.Rendeléskód = r.Rendeléskód
WHERE (rr.Termékkód = 4 OR rr.Termékkód = 5) AND
  ( YEAR( r.SzállításDátuma) = 1995 AND MONTH( r.RendelésDátuma) BETWEEN 1 AND 6)
GROUP BY rr.Termékkód
);


-- --------------------------------------------------------------------------------------------------------------------


-- 4. Melyik a slágertermék, vagyis amibõl a legtöbbet adták el

SELECT t.Termékkód, t.Terméknév, SUM(rr.Mennyiség) AS mennyiség
 FROM rendelésrészletei rr
INNER JOIN termékek t
  ON rr.Termékkód = t.Termékkód
GROUP BY t.Termékkód
ORDER BY mennyiség DESC LIMIT 1;

/* 5. Mely termékek fogytak az átlag felett mennyiség szerint
  növekvõ sorrendben? (a mennyiség mellett szerepeljen a db is) */

-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2018. 04. 06. 13:55:10
-- Server version: 5.5.5-10.1.30-MariaDB
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

USE nwind13ke;


--
-- Create view "SumTbl"
--
DROP VIEW IF EXISTS Sumtbl;
CREATE
-- DEFINER = 'root'@'localhost'
VIEW SumTbl
AS
SELECT
  termékek.Terméknév,
  SUM(rendelésrészletei.Mennyiség) AS össz
FROM rendelésrészletei
  INNER JOIN termékek
    ON rendelésrészletei.Termékkód = termékek.Termékkód
GROUP BY termékek.Terméknév;

--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.1.13.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2018. 04. 06. 14:01:27
-- Server version: 5.5.5-10.1.30-MariaDB
-- Client version: 4.1
-- Please backup your database before running this script
--


SET NAMES 'utf8';

USE nwind13ke;


--
-- Create view "atlag"
--
DROP VIEW IF EXISTS atlag;
CREATE
-- DEFINER = 'root'@'localhost'
VIEW atlag
AS
SELECT
  AVG(s.össz)
FROM sumtbl s;

SELECT
  sumtbl.Terméknév,
  CONCAT(sumtbl.össz, " db") AS Eladva
FROM atlag,
     sumtbl
WHERE atlag.`AVG(s.össz)` < sumtbl.össz
  ORDER BY sumtbl.össz;

DROP VIEW atlag, sumtbl;